### ISSUE TITLE
Implementation on Ubuntu VM

### ISSUE THREAD

**Issue by jasearce** [GEANT-DataPlaneProgramming/int-platforms#7]
Hi, excellent work. I have two main questions about the repo. The first one is related to the name of the issue I'm creating and is about the implementation of this code on a Virtualbox VM. As far as I know, this solutions works on Ubuntu 18.04 with Linux kernel 4.15. I tried to use it on a VirtualBox VM with this specifications and I got everything working fine (I asummed that because I was able to produce packets between h1 and h2 as the testbed says)
![image](https://user-images.githubusercontent.com/56735401/147107058-447ac177-5995-4828-9531-0eef2b604e2a.png)

 but checking the first issue I noticed that when running the application my SO lacks of some virtual interfaces (mainly the one named "int_collection" and the "int_collector"). Here is a pic of the interfaces that ifconfig command showed me. 

![image](https://user-images.githubusercontent.com/56735401/147105744-9d448d58-6a3c-4c7a-bcb0-4bf529fa7931.png)

Do I need to use Ubuntu as a host SO or it is normal this behaviour. The second question is about the pcap file generated on the /tmp/int4app directory. When running the application, I only get two files int_collector.log (which is empty) and the p4s.s1.log (which contains the interfaces configured)

![image](https://user-images.githubusercontent.com/56735401/147106868-809075b7-fb18-451e-ba50-00e0ee4a8b45.png)

Am I doing something wrong? Kinds regards.

**Comment by nhnghia** [comment]
Hi, 

I can reproduce ok the `int-platforms` together with [`int-analytics`](https://github.com/GEANT-DataPlaneProgramming/int-analytics) under Ubuntu 20.04 that is installed inside Virtualbox hosted by macOS. Somehow I do not see `int_collector` neither in the NICs of Ubuntu but the grafana GUI shows well the metric collected by INT. 

Best regards,

**Comment by jasearce** [comment]
Hi,

Thanks for your reply. I noticed that the all the interfaces are created inside the docker implementation but what is strange in th way I tried this solution is that when I generated traffic with the h1_h2_udp_flow.py, there is no .pcap file in the /tmp/p4app_logs directory. What scenario did you try @nhnghia? I can't figure it out what could the problem.

Sincerely,

**Comment by nhnghia** [comment]
I also tried the same I think. I run this command once I got the mininet prompt `h1 python /tmp/host/h1_h2_udp_flow.py`

I also noticed that no .pcap files in `/tmp/p4app_logs`:

```
ls /tmp/p4app_logs/
total 1.7M
drwxr-xr-x  2 root root 4.0K Jan 10 13:42 .
-rw-r--r--  1 root root  628 Jan 10 15:41 p4s.s1.log
-rw-r--r--  1 root root 1.7M Jan 10 15:41 int_collector.log
```

I'm not sure that the .pcap files will be generated automatically unless you use tshark (or tcpdump, etc) to capture the traffic at a node (host or switch) and save it.

**Comment by jasearce** [comment]
For example, in my case when I run the `h1 python /tmp/host/h1_h2_udp_flow.py` I got 0 in the size of the `/tmp/p4app_logs/int_collector.log` file when executing the Python code. I think it should increase the value while the Python code is executing or am I wrong?

**Comment by jasearce** [comment]
Any idea why the `/tmp/p4app_logs/int_collector.log` file is empty when executing `h1 python /tmp/host/h1_h2_udp_flow.py`. I noticed that suddenly the connection with the influxdb at localhost stops and checking processes that are executing with `ps aux | grep python3` this line `python3 /tmp/utils/int_collector_influx.py -i 6000 -H 192.168.0.1:8086 -d 0` appears as `[python3] <defunct>`

` File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1242, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1242, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/utils/int_collector_influx.py", line 482, in <module>
Pkt/s 967    start_udp_server(args)
  File "/tmp/utils/int_collector_influx.py", line 447, in start_udp_server

    influx = influx_client(args)
  File "/tmp/utils/int_collector_influx.py", line 439, in influx_client
    logger.info("Influx client ping response: %s" % client.ping())
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 618, in ping
    expected_response_code=204
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 342, in request
    timeout=self._timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`

**Comment by 10212** [comment]
hello sir.
Can you execute pingall and get the result of the connection? I am in the same situation as we are,  I did not ping successfully. And when I started v1.0, I got the following error message:
 `error setting eth1 up No such device` 
`macvlan_int_1 not` found`
I think we should refer to here[https://github.com/GEANT-DataPlaneProgramming/int-platforms/blob/master/docs/configuration.md](https://github.com/GEANT-DataPlaneProgramming/int-platforms/blob/master/docs/configuration.md) to fix error.
